#!/bin/bash

if [[ -z "$MESHRDF_HOME" ]]; then
    echo "Please provide MESHRDF_HOME environment variable" 1>&2
    exit 1
fi

RDFCAT_JAR=$MESHRDF_HOME/lib/java/jena-rdfcat.jar

if [[ ! -f $RDFCAT_JAR ]]; then 
    echo "$RDFCAT_JAR: not found" 1>&2
    exit 1
fi

java -jar $RDFCAT_JAR $*
